"""empty message

Revision ID: 39e62fd10794
Revises: f9712ab05108
Create Date: 2019-09-16 18:06:27.617426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e62fd10794'
down_revision = 'f9712ab05108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'status')
    # ### end Alembic commands ###
