"""empty message

Revision ID: 4068dfb09597
Revises: ba3c8d47a1e9
Create Date: 2019-09-10 18:10:15.573791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4068dfb09597'
down_revision = 'ba3c8d47a1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
