"""empty message

Revision ID: 5ccc2f564b24
Revises: 4068dfb09597
Create Date: 2019-09-11 18:31:05.529398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccc2f564b24'
down_revision = '4068dfb09597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_id_key', 'customer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customer_id_key', 'customer', ['id'])
    # ### end Alembic commands ###
