"""empty message

Revision ID: ba3c8d47a1e9
Revises: 8e69dceaddc9
Create Date: 2019-09-10 18:08:27.999736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3c8d47a1e9'
down_revision = '8e69dceaddc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_address')
    op.create_unique_constraint(None, 'customer', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.create_table('customer_address',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
